### ISSUE TITLE
Additional Modules Install

### ISSUE THREAD

**Issue by Nova38** [WelterDevelopment/ConTeXt-IDE-WinUI#21]
I would like to be able to use the vim module for code syntax highlighting. I can get it to work with context from my texlive distro, it doesn't appear to be an option in the list of modules i can enable in the app

**Comment by Nova38** [comment]
I believe the only need change is to add it as another option here: 

https://github.com/WelterDevelopment/ConTeXt-IDE-WinUI/blob/a4d06625db1a2b13d8f8342b0e920d0fd965a002/ConTeXt-IDE.Shared/ViewModels/ViewModel.cs#L64z


I have been having some difficulty setting up a dev environment to make a contribution to add it. Could you add some documentation/guide on the setup process of the project?

**Comment by Nova38** [comment]
In particular this is the package that I was hoping to use for syntax highlighting

https://ctan.org/pkg/context-vim?lang=en

**Comment by WelterDevelopment** [comment]
An "Add module installer" button was added. Please right click on gnuplot --> edit to see how a ctan package can be added.
